from django.db import models

class PhnomPenh(models.Model):
    khan_one = models.CharField('Phnom Penh', max_length=120)
    khan_two= models.CharField('Venue Name', max_length=120) 
    khan_three = models.CharField( max_length=120)
    khan_four = models.CharField('Venue Name', max_length=120)
    khan_five = models.CharField( max_length=120)
    khan_six=models.CharField( max_length=120)
    khan_seven = models.CharField( default='khanTi7',max_length=120)
    khan_eight = models.CharField( default='khanTi8',max_length=120)
    khan_nine = models.CharField( default='khanTi9',max_length=120)
    khan_ten = models.CharField( default='khanTi10',max_length=120)
    khan_eleven = models.CharField( default='khanTi11',max_length=120)
    khan_twelve = models.CharField( default='khanTi12',max_length=120)
    khan_thirteen = models.CharField( default='khanTi13',max_length=120)
    khan_fourteen = models.CharField( default='khanTi14',max_length=120)
    khan_fifteen = models.CharField(default="khanti15",max_length=120)
    def __str__(self):
        return self.khan_one
    
    
class Kandal(models.Model):
    First_dis = models.CharField('FirstDristrict',max_length=120)
    Second_dis = models.CharField(default='khanTi7',max_length=120)
    Third_dis = models.CharField(default='khanTi7',max_length=120)
    Fouth_dis = models.CharField(default='khanTi7',max_length=120)
    Fif_dis = models.CharField(default='khanTi7',max_length=120)
    sixth_dis = models.CharField(default='khanTi7',max_length=120)
    seventh_dis=models.CharField(default='khanTi7',max_length=120)
    eight_dis = models.CharField(default='khanTi7',max_length=120)
    nineth_dis = models.CharField(default='khanTi7',max_length=120) 
    tenth_dis = models.CharField(default='khanTi7',max_length=120)
    eleventh_dis = models.CharField(default='khanTi7',max_length=120) 
    twelve_dis = models.CharField(default='twelve_dis',max_length=120)
    def __str__(self):
        return self.First_dis
class Battambang(models.Model):
    btb= models.CharField('btt' ,max_length=120)
    khaeti1 = models.CharField(default='khaeti1', max_length=120)
    khaeti2 = models.CharField(default='khaeti1', max_length=120)
    khaeti3 = models.CharField(default='khaeti1', max_length=120)
    khaeti4 = models.CharField(default='khaeti1', max_length=120)
    khaeti5 = models.CharField(default='khaeti1', max_length=120)
    khaeti6 = models.CharField(default='khaeti1', max_length=120)
    khaeti7 = models.CharField(default='khaeti1', max_length=120)
    khaeti8 = models.CharField(default='khaeti1', max_length=120)
    khaeti9 = models.CharField(default='khaeti1', max_length=120)
    khaeti10 = models.CharField(default='khaeti1', max_length=120)
    khaeti11 = models.CharField(default='khaeti1', max_length=120)
    khaeti12 = models.CharField(default='khaeti1', max_length=120)
    khaeti13 = models.CharField(default='khaeti1', max_length=120)
    khaeti14 = models.CharField(default='khaeti1', max_length=120)

class Pursat(models.Model):
    ps = models.CharField('ps',max_length=120)
    ps1 = models.CharField('ps 1',max_length=120)
    ps2 = models.CharField('ps 1',max_length=120)
    ps3 = models.CharField('ps 1',max_length=120)
    ps4 = models.CharField('ps 1',max_length=120)
    ps5 = models.CharField('ps 1',max_length=120)
    ps6 = models.CharField('ps 1',max_length=120)
    ps7 = models.CharField('ps 1',max_length=120)

class Kampongthom(models.Model):
    kpt = models.CharField('kpt', max_length=120)
    kpt1 = models.CharField('kpt', max_length=120)
    kpt2 = models.CharField('kpt', max_length=120)
    kpt3 = models.CharField('kpt', max_length=120)
    kpt4 = models.CharField('kpt', max_length=120)
    kpt5 = models.CharField('kpt', max_length=120)
    kpt6 = models.CharField('kpt', max_length=120)
    kpt7 = models.CharField('kpt', max_length=120)
    kpt8 = models.CharField('kpt', max_length=120)
    kpt9 = models.CharField('kpt', max_length=120)
class Preasihanouk(models.Model):
    kps = models.CharField('kps', max_length=120)
    kps1 = models.CharField('kps1', max_length=120)
    kps2 = models.CharField('kps2', max_length=120)
    kps3 = models.CharField('kps3', max_length=120)
    kps4 = models.CharField('kps4', max_length=120)
    kps5 = models.CharField('kps5', max_length=120) 
class SteungTreng(models.Model):
    st = models.CharField('st', max_length=120)
    st1 = models.CharField('st1', max_length=120) 
    st2 = models.CharField('st2', max_length=120)
    st3 = models.CharField('st3', max_length=120)
    st4 = models.CharField('st4', max_length=120)
    st5 = models.CharField('st5', max_length=120)
    st6 = models.CharField('st6', max_length=120)
class Bantaeymeanchey(models.Model):
    bmc = models.CharField('bmc',max_length=120)
    bmc1 = models.CharField('bmc1',max_length=120)
    bmc2 = models.CharField('bmc2',max_length=120)
    bmc3 = models.CharField('bmc3',max_length=120)
    bmc4 = models.CharField('bmc4',max_length=120)
    bmc5 = models.CharField('bmc5',max_length=120)
    bmc6 = models.CharField('bmc6',max_length=120)
    bmc7 = models.CharField('bmc7',max_length=120)
    bmc8 = models.CharField('bmc8',max_length=120)
    bmc9 = models.CharField('bmc9',max_length=120)    
class Kampongcham(models.Model):
    kpc = models.CharField('kpc', max_length=120)
    kpc1 = models.CharField('kpc1', max_length=120)
    kpc2 = models.CharField('kpc2', max_length=120)
    kpc3 = models.CharField('kpc3', max_length=120)
    kpc4 = models.CharField('kpc4', max_length=120)
    kpc5 = models.CharField('kpc5', max_length=120)
    kpc6 = models.CharField('kpc6', max_length=120)
    kpc7 = models.CharField('kpc7', max_length=120)
    kpc8 = models.CharField('kpc8', max_length=120)
    kpc9 = models.CharField('kpc9', max_length=120)
    kpc10 = models.CharField('kpc10', max_length=120)
class Siemreap(models.Model):
    sr = models.CharField('sr',max_length=120)
    sr1 = models.CharField('sr1',max_length=120)
    sr2 = models.CharField('sr2',max_length=120)
    sr3 = models.CharField('sr3',max_length=120)
    sr4 = models.CharField('sr4',max_length=120)
    sr5 = models.CharField('sr5',max_length=120)
    sr6 = models.CharField('sr6',max_length=120)
    sr7 = models.CharField('sr7',max_length=120)
    sr8 = models.CharField('sr8',max_length=120)
    sr9 = models.CharField('sr9',max_length=120)
    sr10 = models.CharField('sr10',max_length=120)
    sr11 = models.CharField('sr11',max_length=120)
    sr12 = models.CharField('sr12',max_length=120)
class Preyveng(models.Model):
    pv = models.CharField('pv',max_length=120)
    pv1 = models.CharField('pv1',max_length=120)
    pv2 = models.CharField('pv2',max_length=120)
    pv3 = models.CharField('pv3',max_length=120)
    pv4 = models.CharField('pv4',max_length=120)
    pv5 = models.CharField('pv5',max_length=120)
    pv6 = models.CharField('pv6',max_length=120)
    pv7 = models.CharField('pv7',max_length=120)
    pv8 = models.CharField('pv8',max_length=120)
    pv9 = models.CharField('pv9',max_length=120)
    pv10 = models.CharField('pv10',max_length=120)
    pv11 = models.CharField('pv11',max_length=120)
    pv12 = models.CharField('pv12',max_length=120)
    pv13 = models.CharField('pv13',max_length=120)
class Svayreang(models.Model):
    svr = models.CharField('svr', max_length=120)
    svr1 = models.CharField('svr1', max_length=120)
    svr2 = models.CharField('svr2', max_length=120)
    svr3 = models.CharField('svr3', max_length=120)
    svr4 = models.CharField('svr4', max_length=120)
    svr5 = models.CharField('svr5', max_length=120)
    svr6 = models.CharField('svr6', max_length=120)
    svr7 = models.CharField('svr7', max_length=120)
    svr8 = models.CharField('svr8', max_length=120)
class Takeo(models.Model):
    tk = models.CharField('tk',max_length=120)
    tk1 = models.CharField('tk1',max_length=120)
    tk2 = models.CharField('tk2',max_length=120)
    tk3 = models.CharField('tk3',max_length=120)
    tk4 = models.CharField('tk4',max_length=120)
    tk5 = models.CharField('tk5',max_length=120)
    tk6 = models.CharField('tk6',max_length=120)
    tk7 = models.CharField('tk7',max_length=120)
    tk8 = models.CharField('tk8',max_length=120)
    tk9 = models.CharField('tk9',max_length=120)
    tk10 = models.CharField('tk10',max_length=120)
class Tbongkhmum(models.Model):
    tb = models.CharField('tb',max_length=120)
    tb1 = models.CharField('tb1',max_length=120)
    tb2 = models.CharField('tb2',max_length=120)
    tb3 = models.CharField('tb3',max_length=120)
    tb4 = models.CharField('tb4',max_length=120)
    tb5 = models.CharField('tb5',max_length=120)
    tb6 = models.CharField('tb6',max_length=120)
    tb7 = models.CharField('tb7',max_length=120) 
class Kampot(models.Model):
    kp = models.CharField('kp',max_length=120)
    kp1 = models.CharField('kp1',max_length=120)
    kp2 = models.CharField('kp2',max_length=120)
    kp3 = models.CharField('kp3',max_length=120)
    kp4 = models.CharField('kp4',max_length=120)
    kp5 = models.CharField('kp5',max_length=120)
    kp6 = models.CharField('kp6',max_length=120)
    kp7 = models.CharField('kp7',max_length=120)
    kp8 = models.CharField('kp8',max_length=120)
class Kampongspeu(models.Model):
    speu = models.CharField('speu',max_length=120)
    speu1 = models.CharField('speu1',max_length=120)
    speu2 = models.CharField('speu2',max_length=120)
    speu3 = models.CharField('speu3',max_length=120)
    speu4 = models.CharField('speu4',max_length=120)
    speu5 = models.CharField('speu5',max_length=120)
    speu6 = models.CharField('speu6',max_length=120)
    speu7 = models.CharField('speu7',max_length=120)
    speu8 = models.CharField('speu8',max_length=120)
class KampongChnang(models.Model):
    kongrey = models.CharField('kongrey',max_length=120)
    kongrey1 = models.CharField('kongrey1',max_length=120)
    kongrey2 = models.CharField('kongrey2',max_length=120)
    kongrey3 = models.CharField('kongrey3',max_length=120)
    kongrey4 = models.CharField('kongrey4',max_length=120)
    kongrey5 = models.CharField('kongrey5',max_length=120)
    kongrey6 = models.CharField('kongrey6',max_length=120)
    kongrey7 = models.CharField('kongrey7',max_length=120)
    kongrey8 = models.CharField('kongrey8',max_length=120)
class Kohkong(models.Model):
    Gpath = models.CharField('Gpath',max_length=120)
    Gpath1 = models.CharField('Gpath1',max_length=120)
    Gpath2 = models.CharField('Gpath2',max_length=120)
    Gpath3 = models.CharField('Gpath3',max_length=120)
    Gpath4 = models.CharField('Gpath4',max_length=120)
    Gpath5 = models.CharField('Gpath5',max_length=120)
    Gpath6 = models.CharField('Gpath6',max_length=120)
    Gpath7 = models.CharField('Gpath7',max_length=120) 
class kratie(models.Model):
    dolphin = models.CharField('dolphin',max_length=120)
    dolphin1 = models.CharField('dolphin1',max_length=120)
    dolphin2 = models.CharField('dolphin2',max_length=120)
    dolphin3 = models.CharField('dolphin3',max_length=120)
    dolphin4 = models.CharField('dolphin4',max_length=120)
    dolphin5 = models.CharField('dolphin5',max_length=120)
    dolphin6 = models.CharField('dolphin6',max_length=120)
class PreasVihea(models.Model):
    fkthailand = models.CharField('fkthailand',max_length=120)
    fkthailand1 = models.CharField('fkthailand1',max_length=120)
    fkthailand2 = models.CharField('fkthailand2',max_length=120)
    fkthailand3 = models.CharField('fkthailand3',max_length=120)
    fkthailand4 = models.CharField('fkthailand4',max_length=120)
    fkthailand5 = models.CharField('fkthailand5',max_length=120)
    fkthailand6 = models.CharField('fkthailand6',max_length=120)
    fkthailand7 = models.CharField('fkthailand7',max_length=120)
    fkthailand8 = models.CharField('fkthailand8',max_length=120)
class Mondolkiri(models.Model):
    indigenous = models.CharField('indigenous',max_length=120)
    indigenous1 = models.CharField('indigenous1',max_length=120)
    indigenous2 = models.CharField('indigenous2',max_length=120)
    indigenous3 = models.CharField('indigenous3',max_length=120)
    indigenous4 = models.CharField('indigenous4',max_length=120)
    indigenous5 = models.CharField('indigenous5',max_length=120)
class Ratanakiri(models.Model):
    yeaklorm = models.CharField('yeaklom',max_length=120)
    yeaklorm1 = models.CharField('yeaklom1',max_length=120)
    yeaklorm2 = models.CharField('yeaklom2',max_length=120)
    yeaklorm3 = models.CharField('yeaklom3',max_length=120)
    yeaklorm4 = models.CharField('yeaklom4',max_length=120)
    yeaklorm5 = models.CharField('yeaklom5',max_length=120)
    yeaklorm6 = models.CharField('yeaklom6',max_length=120)
    yeaklorm7 = models.CharField('yeaklom7',max_length=120)
    yeaklorm8 = models.CharField('yeaklom8',max_length=120)
    yeaklorm9 = models.CharField('yeaklom9',max_length=120)
class Oudormeanchey(models.Model):
    khaet_bos_tamok = models.CharField('tamok',max_length=120)
    tamok1 = models.CharField('tamok1',max_length=120)
    tamok2 = models.CharField('tamok2',max_length=120)
    tamok3 = models.CharField('tamok3',max_length=120)
    tamok4 = models.CharField('tamok4',max_length=120)
    tamok5 = models.CharField('tamok5',max_length=120)
class Kep(models.Model):
    smallest = models.CharField('smallest',max_length=120)
    smallest1 = models.CharField('smallest1',max_length=120)
    smallest2 = models.CharField('smallest2',max_length=120)
class Pailin(models.Model):
    diamond = models.CharField('jav_jit',max_length=120)
    diamond1 = models.CharField('diamond1',max_length=120)
    diamond2 = models.CharField('diamond2',max_length=120)
    
       
     