# Generated by Django 5.0.7 on 2024-08-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event District')),
                ('event_date', models.DateTimeField(verbose_name='Event Province')),
                ('manager', models.CharField(max_length=120)),
                ('description', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myclubuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=120)),
                ('Lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('zip_code', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('web', models.URLField(verbose_name='website address')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='db_app.myclubuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='Venue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='db_app.venue'),
        ),
    ]
