# Generated by Django 5.0.7 on 2024-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_event_myclubuser_venue_delete_book_event_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis1', models.CharField(max_length=120, verbose_name='Event District')),
                ('dis2', models.CharField(max_length=120)),
                ('dis3', models.CharField(max_length=120)),
                ('dis4', models.CharField(max_length=120)),
                ('dis5', models.CharField(max_length=120)),
                ('dis6', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.CharField(max_length=120),
        ),
    ]
