# Generated by Django 5.0.7 on 2024-08-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_pp_alter_venue_email_address_alter_venue_web'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PP',
            new_name='PhnomPenh',
        ),
    ]
