# Generated by Django 5.0.7 on 2024-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0004_rename_pp_phnompenh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phnompenh',
            name='dis1',
            field=models.CharField(max_length=120),
        ),
    ]
