# Generated by Django 5.0.7 on 2024-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0005_alter_phnompenh_dis1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_dis', models.CharField(max_length=120, verbose_name='FirstDristrict')),
                ('Second_dis', models.CharField(max_length=120)),
                ('Third_dis', models.CharField(max_length=120)),
                ('Fouth_dis', models.CharField(max_length=120)),
                ('Fif_dis', models.CharField(max_length=120)),
                ('sixth_dis', models.CharField(max_length=120)),
                ('seventh_dis', models.CharField(max_length=120)),
                ('eight_dis', models.CharField(max_length=120)),
                ('nineth_dis', models.CharField(max_length=120)),
                ('tenth_dis', models.CharField(max_length=120)),
                ('eleventh_dis', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='phnompenh',
            old_name='dis1',
            new_name='fdis',
        ),
    ]
