# Generated by Django 5.0.7 on 2024-08-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0006_kandal_rename_dis1_phnompenh_fdis'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='khan_eight',
            field=models.CharField(default='khanTi8', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_eleven',
            field=models.CharField(default='khanTi11', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_fourteen',
            field=models.CharField(default='khanTi14', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_nine',
            field=models.CharField(default='khanTi9', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_seven',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_ten',
            field=models.CharField(default='khanTi10', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_thirteen',
            field=models.CharField(default='khanTi13', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='khan_twelve',
            field=models.CharField(default='khanTi12', max_length=120),
        ),
    ]
