# Generated by Django 5.0.7 on 2024-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0007_venue_khan_eight_venue_khan_eleven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandal',
            name='Fif_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='Fouth_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='Second_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='Third_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='eight_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='eleventh_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='nineth_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='seventh_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='sixth_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
        migrations.AlterField(
            model_name='kandal',
            name='tenth_dis',
            field=models.CharField(default='khanTi7', max_length=120),
        ),
    ]
