# Generated by Django 5.0.7 on 2024-08-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0008_alter_kandal_fif_dis_alter_kandal_fouth_dis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='PhnomPenh',
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Phnom Penh'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Myclubuser',
        ),
    ]
