# Generated by Django 5.0.7 on 2024-08-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0009_remove_event_venue_remove_event_attendees_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='PhnomPenh',
        ),
    ]
