# Generated by Django 5.0.7 on 2024-08-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0011_rename_email_address_phnompenh_khan_five_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battambang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btb', models.CharField(max_length=120, verbose_name='btt')),
                ('khaeti1', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti2', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti3', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti4', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti5', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti6', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti7', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti8', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti9', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti10', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti11', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti12', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti13', models.CharField(default='khaeti1', max_length=120)),
                ('khaeti14', models.CharField(default='khaeti1', max_length=120)),
            ],
        ),
    ]
