# Generated by Django 5.0.7 on 2024-08-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0012_battambang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pursat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps', models.CharField(max_length=120, verbose_name='ps')),
                ('ps1', models.CharField(max_length=120, verbose_name='ps 1')),
                ('ps2', models.CharField(max_length=120, verbose_name='ps 1')),
                ('ps3', models.CharField(max_length=120, verbose_name='ps 1')),
                ('ps4', models.CharField(max_length=120, verbose_name='ps 1')),
                ('ps5', models.CharField(max_length=120, verbose_name='ps 1')),
                ('ps6', models.CharField(max_length=120, verbose_name='ps 1')),
                ('ps7', models.CharField(max_length=120, verbose_name='ps 1')),
            ],
        ),
    ]
