# Generated by Django 5.0.7 on 2024-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0013_pursat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampongthom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpt', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt1', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt2', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt3', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt4', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt5', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt6', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt7', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt8', models.CharField(max_length=120, verbose_name='kpt')),
                ('kpt9', models.CharField(max_length=120, verbose_name='kpt')),
            ],
        ),
    ]
