# Generated by Django 5.0.7 on 2024-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0014_kampongthom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preasihanouk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kps', models.CharField(max_length=120, verbose_name='kps')),
                ('kps1', models.CharField(max_length=120, verbose_name='kps1')),
                ('kps2', models.CharField(max_length=120, verbose_name='kps2')),
                ('kps3', models.CharField(max_length=120, verbose_name='kps3')),
                ('kps4', models.CharField(max_length=120, verbose_name='kps4')),
                ('kps5', models.CharField(max_length=120, verbose_name='kps5')),
            ],
        ),
    ]
