# Generated by Django 5.0.7 on 2024-08-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0015_preasihanouk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteungTreng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st', models.CharField(max_length=120, verbose_name='st')),
                ('st1', models.CharField(max_length=120, verbose_name='st1')),
                ('st2', models.CharField(max_length=120, verbose_name='st2')),
                ('st3', models.CharField(max_length=120, verbose_name='st3')),
                ('st4', models.CharField(max_length=120, verbose_name='st4')),
                ('st5', models.CharField(max_length=120, verbose_name='st5')),
                ('st6', models.CharField(max_length=120, verbose_name='st6')),
            ],
        ),
    ]
