# Generated by Django 5.0.7 on 2024-08-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0016_steungtreng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bantaeymeanchey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmc', models.CharField(max_length=120, verbose_name='bmc')),
                ('bmc1', models.CharField(max_length=120, verbose_name='bmc1')),
                ('bmc2', models.CharField(max_length=120, verbose_name='bmc2')),
                ('bmc3', models.CharField(max_length=120, verbose_name='bmc3')),
                ('bmc4', models.CharField(max_length=120, verbose_name='bmc4')),
                ('bmc5', models.CharField(max_length=120, verbose_name='bmc5')),
                ('bmc6', models.CharField(max_length=120, verbose_name='bmc6')),
                ('bmc7', models.CharField(max_length=120, verbose_name='bmc7')),
                ('bmc8', models.CharField(max_length=120, verbose_name='bmc8')),
                ('bmc9', models.CharField(max_length=120, verbose_name='bmc9')),
            ],
        ),
    ]
