# Generated by Django 5.0.7 on 2024-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0017_bantaeymeanchey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampongcham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpc', models.CharField(max_length=120, verbose_name='kpc')),
                ('kpc1', models.CharField(max_length=120, verbose_name='kpc1')),
                ('kpc2', models.CharField(max_length=120, verbose_name='kpc2')),
                ('kpc3', models.CharField(max_length=120, verbose_name='kpc3')),
                ('kpc4', models.CharField(max_length=120, verbose_name='kpc4')),
                ('kpc5', models.CharField(max_length=120, verbose_name='kpc5')),
                ('kpc6', models.CharField(max_length=120, verbose_name='kpc6')),
                ('kpc7', models.CharField(max_length=120, verbose_name='kpc7')),
                ('kpc8', models.CharField(max_length=120, verbose_name='kpc8')),
                ('kpc9', models.CharField(max_length=120, verbose_name='kpc9')),
                ('kpc10', models.CharField(max_length=120, verbose_name='kpc10')),
            ],
        ),
    ]
