# Generated by Django 5.0.7 on 2024-08-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0018_kampongcham'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siemreap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.CharField(max_length=120, verbose_name='sr')),
                ('sr1', models.CharField(max_length=120, verbose_name='sr1')),
                ('sr2', models.CharField(max_length=120, verbose_name='sr2')),
                ('sr3', models.CharField(max_length=120, verbose_name='sr3')),
                ('sr4', models.CharField(max_length=120, verbose_name='sr4')),
                ('sr5', models.CharField(max_length=120, verbose_name='sr5')),
                ('sr6', models.CharField(max_length=120, verbose_name='sr6')),
                ('sr7', models.CharField(max_length=120, verbose_name='sr7')),
                ('sr8', models.CharField(max_length=120, verbose_name='sr8')),
                ('sr9', models.CharField(max_length=120, verbose_name='sr9')),
                ('sr10', models.CharField(max_length=120, verbose_name='sr10')),
                ('sr11', models.CharField(max_length=120, verbose_name='sr11')),
                ('sr12', models.CharField(max_length=120, verbose_name='sr12')),
            ],
        ),
    ]
