# Generated by Django 5.0.7 on 2024-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0019_siemreap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preyveng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pv', models.CharField(max_length=120, verbose_name='pv')),
                ('pv1', models.CharField(max_length=120, verbose_name='pv1')),
                ('pv2', models.CharField(max_length=120, verbose_name='pv2')),
                ('pv3', models.CharField(max_length=120, verbose_name='pv3')),
                ('pv4', models.CharField(max_length=120, verbose_name='pv4')),
                ('pv5', models.CharField(max_length=120, verbose_name='pv5')),
                ('pv6', models.CharField(max_length=120, verbose_name='pv6')),
                ('pv7', models.CharField(max_length=120, verbose_name='pv7')),
                ('pv8', models.CharField(max_length=120, verbose_name='pv8')),
                ('pv9', models.CharField(max_length=120, verbose_name='pv9')),
                ('pv10', models.CharField(max_length=120, verbose_name='pv10')),
                ('pv11', models.CharField(max_length=120, verbose_name='pv11')),
                ('pv12', models.CharField(max_length=120, verbose_name='pv12')),
                ('pv13', models.CharField(max_length=120, verbose_name='pv13')),
            ],
        ),
    ]
