# Generated by Django 5.0.7 on 2024-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0020_preyveng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Svayreang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svr', models.CharField(max_length=120, verbose_name='svr')),
                ('svr1', models.CharField(max_length=120, verbose_name='svr1')),
                ('svr2', models.CharField(max_length=120, verbose_name='svr2')),
                ('svr3', models.CharField(max_length=120, verbose_name='svr3')),
                ('svr4', models.CharField(max_length=120, verbose_name='svr4')),
                ('svr5', models.CharField(max_length=120, verbose_name='svr5')),
                ('svr6', models.CharField(max_length=120, verbose_name='svr6')),
                ('svr7', models.CharField(max_length=120, verbose_name='svr7')),
                ('svr8', models.CharField(max_length=120, verbose_name='svr8')),
            ],
        ),
    ]
