# Generated by Django 5.0.7 on 2024-08-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0021_svayreang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk', models.CharField(max_length=120, verbose_name='tk')),
                ('tk1', models.CharField(max_length=120, verbose_name='tk1')),
                ('tk2', models.CharField(max_length=120, verbose_name='tk2')),
                ('tk3', models.CharField(max_length=120, verbose_name='tk3')),
                ('tk4', models.CharField(max_length=120, verbose_name='tk4')),
                ('tk5', models.CharField(max_length=120, verbose_name='tk5')),
                ('tk6', models.CharField(max_length=120, verbose_name='tk6')),
                ('tk7', models.CharField(max_length=120, verbose_name='tk7')),
                ('tk8', models.CharField(max_length=120, verbose_name='tk8')),
                ('tk9', models.CharField(max_length=120, verbose_name='tk9')),
                ('tk10', models.CharField(max_length=120, verbose_name='tk10')),
            ],
        ),
    ]
