# Generated by Django 5.0.7 on 2024-08-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0022_takeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbongkhmum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb', models.CharField(max_length=120, verbose_name='tb')),
                ('tb1', models.CharField(max_length=120, verbose_name='tb1')),
                ('tb2', models.CharField(max_length=120, verbose_name='tb2')),
                ('tb3', models.CharField(max_length=120, verbose_name='tb3')),
                ('tb4', models.CharField(max_length=120, verbose_name='tb4')),
                ('tb5', models.CharField(max_length=120, verbose_name='tb5')),
                ('tb6', models.CharField(max_length=120, verbose_name='tb6')),
                ('tb7', models.CharField(max_length=120, verbose_name='tb7')),
            ],
        ),
    ]
