# Generated by Django 5.0.7 on 2024-08-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0023_tbongkhmum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp', models.CharField(max_length=120, verbose_name='kp')),
                ('kp1', models.CharField(max_length=120, verbose_name='kp1')),
                ('kp2', models.CharField(max_length=120, verbose_name='kp2')),
                ('kp3', models.CharField(max_length=120, verbose_name='kp3')),
                ('kp4', models.CharField(max_length=120, verbose_name='kp4')),
                ('kp5', models.CharField(max_length=120, verbose_name='kp5')),
                ('kp6', models.CharField(max_length=120, verbose_name='kp6')),
                ('kp7', models.CharField(max_length=120, verbose_name='kp7')),
                ('kp8', models.CharField(max_length=120, verbose_name='kp8')),
            ],
        ),
    ]
