# Generated by Django 5.0.7 on 2024-08-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0024_kampot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kampongspeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speu', models.CharField(max_length=120, verbose_name='speu')),
                ('speu1', models.CharField(max_length=120, verbose_name='speu1')),
                ('speu2', models.CharField(max_length=120, verbose_name='speu2')),
                ('speu3', models.CharField(max_length=120, verbose_name='speu3')),
                ('speu4', models.CharField(max_length=120, verbose_name='speu4')),
                ('speu5', models.CharField(max_length=120, verbose_name='speu5')),
                ('speu6', models.CharField(max_length=120, verbose_name='speu6')),
                ('speu7', models.CharField(max_length=120, verbose_name='speu7')),
                ('speu8', models.CharField(max_length=120, verbose_name='speu8')),
            ],
        ),
    ]
