# Generated by Django 5.0.7 on 2024-08-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0025_kampongspeu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KampongChnang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kongrey', models.CharField(max_length=120, verbose_name='kongrey')),
                ('kongrey1', models.CharField(max_length=120, verbose_name='kongrey1')),
                ('kongrey2', models.CharField(max_length=120, verbose_name='kongrey2')),
                ('kongrey3', models.CharField(max_length=120, verbose_name='kongrey3')),
                ('kongrey4', models.CharField(max_length=120, verbose_name='kongrey4')),
                ('kongrey5', models.CharField(max_length=120, verbose_name='kongrey5')),
                ('kongrey6', models.CharField(max_length=120, verbose_name='kongrey6')),
                ('kongrey7', models.CharField(max_length=120, verbose_name='kongrey7')),
                ('kongrey8', models.CharField(max_length=120, verbose_name='kongrey8')),
            ],
        ),
    ]
