# Generated by Django 5.0.7 on 2024-08-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0027_kohkong'),
    ]

    operations = [
        migrations.CreateModel(
            name='kratie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolphin', models.CharField(max_length=120, verbose_name='dolphin')),
                ('dolphin1', models.CharField(max_length=120, verbose_name='dolphin1')),
                ('dolphin2', models.CharField(max_length=120, verbose_name='dolphin2')),
                ('dolphin3', models.CharField(max_length=120, verbose_name='dolphin3')),
                ('dolphin4', models.CharField(max_length=120, verbose_name='dolphin4')),
                ('dolphin5', models.CharField(max_length=120, verbose_name='dolphin5')),
                ('dolphin6', models.CharField(max_length=120, verbose_name='dolphin6')),
            ],
        ),
    ]
