# Generated by Django 5.0.7 on 2024-08-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0029_preasvihea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mondolkiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indigenous', models.CharField(max_length=120, verbose_name='indigenous')),
                ('indigenous1', models.CharField(max_length=120, verbose_name='indigenous1')),
                ('indigenous2', models.CharField(max_length=120, verbose_name='indigenous2')),
                ('indigenous3', models.CharField(max_length=120, verbose_name='indigenous3')),
                ('indigenous4', models.CharField(max_length=120, verbose_name='indigenous4')),
                ('indigenous5', models.CharField(max_length=120, verbose_name='indigenous5')),
            ],
        ),
    ]
