# Generated by Django 5.0.7 on 2024-08-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0030_mondolkiri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratanakiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeaklorm', models.CharField(max_length=120, verbose_name='yeaklom')),
                ('yeaklorm1', models.CharField(max_length=120, verbose_name='yeaklom1')),
                ('yeaklorm2', models.CharField(max_length=120, verbose_name='yeaklom2')),
                ('yeaklorm3', models.CharField(max_length=120, verbose_name='yeaklom3')),
                ('yeaklorm4', models.CharField(max_length=120, verbose_name='yeaklom4')),
                ('yeaklorm5', models.CharField(max_length=120, verbose_name='yeaklom5')),
                ('yeaklorm6', models.CharField(max_length=120, verbose_name='yeaklom6')),
                ('yeaklorm7', models.CharField(max_length=120, verbose_name='yeaklom7')),
                ('yeaklorm8', models.CharField(max_length=120, verbose_name='yeaklom8')),
                ('yeaklorm9', models.CharField(max_length=120, verbose_name='yeaklom9')),
            ],
        ),
    ]
