# Generated by Django 5.0.7 on 2024-08-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0031_ratanakiri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oudormeanchey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamok', models.CharField(max_length=120, verbose_name='tamok')),
                ('tamok1', models.CharField(max_length=120, verbose_name='tamok1')),
                ('tamok2', models.CharField(max_length=120, verbose_name='tamok2')),
                ('tamok3', models.CharField(max_length=120, verbose_name='tamok3')),
                ('tamok4', models.CharField(max_length=120, verbose_name='tamok4')),
                ('tamok5', models.CharField(max_length=120, verbose_name='tamok5')),
            ],
        ),
    ]
