# Generated by Django 5.0.7 on 2024-08-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0032_oudormeanchey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oudormeanchey',
            old_name='tamok',
            new_name='khaet_bos_tamok',
        ),
    ]
